apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      containers:
      - name: pong-app
        image: takionqoy/getting-started:pong-app
        ports:
        - containerPort: 80
