apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      containers:
      - name: pong-app
        image: {{ .Values.image.repository | default "takionqoy/getting-started" }}:{{ .Values.image.tag | default "latest" }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
